
--- 
title:  Python报错：Traceback ():File 路径, line 12, in ＜module＞，AttributeError以及NameError的原因及解决方法 
tags: []
categories: [] 

---
>  
 本文主要讲解Python引入包，报错：AttributeError的原因及解决方法。 日期：2023年5月10日 作者：任聪聪 python3.9.6 


### 报错现象

<img src="https://img-blog.csdnimg.cn/def003c4257c419fa6bcbd5092a119ee.png" alt="在这里插入图片描述"> 一般文本报错为：

```
Traceback (most recent call last):
  File "E:\路径\文件.py", line 12, in &lt;module&gt;
    返回值= 函数(输入值)
AttributeError: module '模块名称' has no attribute '函数名'

```

### 
